### ISSUE TITLE
When an option is set to false in the toolbarConfig the icon is still displayed

### ISSUE THREAD

**Issue by fsaillofest** [predixdesignsystem/px-vis-timeseries#65]
Hi,

I have an issue with the toolbar configuration while using px-vis-timeseries.

### Actual behavior
When I set to false the advancedZoom attribute in the config:
{
  "config": {
    "advancedZoom": false,
    "pan": true,
    "tooltip": true
  }
}
The zoom button is still displayed and active in the toolbar.
The only way to not have the zoom button in the toolbar is to not have the advancedZoom attribute in the config object:
{
  "config": {
    "pan": true,
    "tooltip": true
  }
}
but that mean I can't simply update the toolbar config with a variable in my code like this:
config.advancedZoom = myAdvancedZoomBoolean;

### Expected behavior
I would expect a button to not be displayed in the toolbar when the corresponding attribute is set to false in the config.

## Environment :
Chrome v61 on MacOSX 10.12

**Comment by benoitjchevalier** [comment]
This is the expected behavior, there are still various ways you could update your config based on a boolean: delete/add the property or keep different configs and switch them based on your boolean.

Your suggestion makes sense though, my only concern being that this is technically a breaking change (if someone has it misconfigured with false right now they might see some button disappear with the upgrade). I'll probably consider it for the next major release.

**Comment by benoitjchevalier** [comment]
Implemented in the `register` branch, will be released as part of the next major

**Comment by benoitjchevalier** [comment]
released in `4.0.0`
