### ISSUE TITLE
Extra space inserted between start of axis and points plotting started.

### ISSUE THREAD

**Issue by Sd100** [predixdesignsystem/px-vis-timeseries#82]
Hi,
ISSUE: the region marked the image attached below shows extra space is being inserted automatically.
![samplepic](https://user-images.githubusercontent.com/37838320/38674068-d143f43a-3e70-11e8-85ae-28989c1e7f51.PNG)

Steps to reproduce:
x-axis-type: "ordinal",
And the values being sent in chartData for x-axis are in String form. and the chart is plotted.

Required:
Need a solution to remove the extra space inserted or is this the expected behavior in px-vis-timeseries when axisType is ordinal? Please suggest a solution or a workaround to remove this space via xAxisconfig or Axis properties.

**Comment by nonmetalhail** [comment]
Ordinal axis type is not supported. Use XY chart

**Comment by nonmetalhail** [comment]
To clarify further, the timeseries chart is intended only for continuous timeseries data. XY chart is more generic and supports ordinal axis types. On that chart, you'll be able to change properties such as the padding you're concerned about. But you'll also have to specify a axis formatter to display your ticks as dates instead of just timestamps.
